/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbexperiment;


import static dbexperiment.MySQLConnection.conn;
import static dbexperiment.MySQL2.conn2;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author hp
 */
public class DBWorking extends javax.swing.JFrame {

    /**
     * Creates new form DBWorking
     */
     int xMouse;
    int yMouse;
    static Statement stmt=null;
    static ResultSet rs1;
    static Connection con;
    public DBWorking() {
        
        initComponents();
        jLabel13.setVisible(false);
        jLabel15.setVisible(false);
        try
        {
          Login ln = new Login();
          friendreg1.setText(ln.reg);  
         DatabaseMetaData dbmd = MySQLConnection.conn.getMetaData();
          String[] types = {"TABLE"};
          ResultSet rs = dbmd.getTables(null,null, "%", types);
          ytable.setText("");
            while(rs.next())
            {
             ytable.append(rs.getString("TABLE_NAME"));
             ytable.append("\n");
            }
            String CONN_STRIN="jdbc:mysql://172.31.100.41:3306/"+"db2017CA21";
            String usr="2017CA21";
            String passw="2@17C@21";
            con = DriverManager.getConnection(CONN_STRIN,usr,passw);
            stmt =con.createStatement();
            System.out.println("Testing");
            String qr = "select Name,Email from studentinfo where RegNo='"+ln.reg+"'";
            System.out.println(qr);
            rs1 = stmt.executeQuery(qr);
            
            while(rs1.next())
            {
                usernametext.setText(rs1.getString(1));
                useremailtext.setText(rs1.getString(2));
            }
            String str = "/dbexperiment/photos/" + ln.reg + ".png";
            profilepic.setIcon(new javax.swing.ImageIcon(getClass().getResource(str)));
        }
        catch(Exception e)
        {}
        finally
        {
            try
            {
            conn.close();
            }
            catch(Exception e)
            {}
        }
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        usernametext = new javax.swing.JTextField();
        useremailtext = new javax.swing.JTextField();
        profilepic = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ytable = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        friendreg = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ftable = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        querytable = new javax.swing.JTextArea();
        friendreg1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        friendreg2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome !!!");

        usernametext.setEditable(false);
        usernametext.setBackground(new java.awt.Color(0, 0, 102));
        usernametext.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 36)); // NOI18N
        usernametext.setForeground(new java.awt.Color(255, 255, 255));
        usernametext.setBorder(null);

        useremailtext.setEditable(false);
        useremailtext.setBackground(new java.awt.Color(0, 0, 102));
        useremailtext.setFont(new java.awt.Font("Segoe UI Semilight", 2, 18)); // NOI18N
        useremailtext.setForeground(new java.awt.Color(255, 255, 255));
        useremailtext.setToolTipText("");
        useremailtext.setBorder(null);
        useremailtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useremailtextActionPerformed(evt);
            }
        });

        profilepic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbexperiment/photos/icons8_Admin_52px.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbexperiment/images/icons8_Delete_32px_2.png"))); // NOI18N
        jLabel3.setText("jLabel2");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 40, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(profilepic, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(useremailtext, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(usernametext, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(usernametext, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(useremailtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(profilepic, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 190));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ytable.setEditable(false);
        ytable.setColumns(20);
        ytable.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        ytable.setForeground(new java.awt.Color(0, 204, 0));
        ytable.setRows(5);
        ytable.setBorder(null);
        jScrollPane1.setViewportView(ytable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 310, 230));

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Get Friend SQL Query");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 250, 40));

        jLabel4.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("Your Tables");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 30));

        friendreg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        friendreg.setText("2017CA");
        friendreg.setBorder(null);
        jPanel3.add(friendreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 110, 30));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 100, 10));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbexperiment/images/icons8_View_24px.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 40, -1, 30));

        ftable.setEditable(false);
        ftable.setColumns(20);
        ftable.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        ftable.setForeground(new java.awt.Color(0, 0, 102));
        ftable.setRows(5);
        ftable.setBorder(null);
        jScrollPane2.setViewportView(ftable);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 320, 230));

        querytable.setColumns(20);
        querytable.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        querytable.setRows(5);
        jScrollPane3.setViewportView(querytable);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 420, 230));

        friendreg1.setEditable(false);
        friendreg1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        friendreg1.setBorder(null);
        jPanel3.add(friendreg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, 30));

        jLabel5.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Your Friends Tables");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 230, 30));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 170, 10));

        friendreg2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        friendreg2.setBorder(null);
        jPanel3.add(friendreg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 160, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Table Name :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 42, -1, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbexperiment/images/icons8_MySQL_24px.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, -1, 30));

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));

        jLabel9.setBackground(new java.awt.Color(0, 0, 255));
        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 2, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Developed by Lokesh Chandra");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 870, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 1050, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbexperiment/images/icons8_Refresh_24px.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, 30));

        jLabel12.setFont(new java.awt.Font("Sitka Subheading", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 51));
        jLabel12.setText("Copy Table with all Table data");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 330, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbexperiment/images/icons8_Copy_24px_2.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 350, 40, 40));

        jLabel14.setFont(new java.awt.Font("Sitka Subheading", 1, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 51));
        jLabel14.setText("Copy Only Table Structure");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 290, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbexperiment/images/icons8_Data_Backup_26px_1.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1050, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void useremailtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useremailtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useremailtextActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        String freg = friendreg.getText();
        getvaluein(freg);
    }//GEN-LAST:event_jLabel6MouseClicked
  static String tname;
    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        String fregq = friendreg.getText();
        tname = friendreg2.getText();
        MySQL3 msl = new MySQL3(fregq);
        
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        String fr = friendreg.getText();
        String frtable = friendreg2.getText();
        String ownreg = friendreg1.getText();
        test=null;
        MySQL4 ms4 = new MySQL4(fr,ownreg,frtable);
        
    }//GEN-LAST:event_jLabel13MouseClicked
    public static int ref = 0;
    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        ref++;
        MySQLConnection msc = new MySQLConnection(friendreg1.getText());
        
    }//GEN-LAST:event_jLabel10MouseClicked
    public static String test=null;
    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        String fr = friendreg.getText();
        String frtable = friendreg2.getText();
        String ownreg = friendreg1.getText();
        test="on";
        MySQL4 ms4 = new MySQL4(fr,ownreg,frtable);
        
    }//GEN-LAST:event_jLabel15MouseClicked
    
    public void getvaluein(String freg)
    {
        MySQL2 msc=new MySQL2(freg);
      
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBWorking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBWorking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBWorking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBWorking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBWorking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField friendreg;
    public javax.swing.JTextField friendreg1;
    public javax.swing.JTextField friendreg2;
    public static javax.swing.JTextArea ftable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JLabel profilepic;
    public static javax.swing.JTextArea querytable;
    public javax.swing.JTextField useremailtext;
    public javax.swing.JTextField usernametext;
    public static javax.swing.JTextArea ytable;
    // End of variables declaration//GEN-END:variables
}
